# Generated by Django 5.0.1 on 2024-01-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_alter_review_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_author',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
